### ISSUE TITLE
仅仅需要爬取http://lib.cqvip.com/Qikan/Journal/JournalGuid期刊信息，这个脚本可以吗？

### ISSUE THREAD

**Issue by wentong2org** [hcj5206/CnkiAndCqvipCrawler#1]
纯粹小白。仅仅需要爬取http://lib.cqvip.com/Qikan/Journal/JournalGuid期刊信息，这个脚本可以吗？

**Comment by hcj5206** [comment]
> 纯粹小白。仅仅需要爬取[http://lib.cqvip.com/Qikan/Journal/JournalGuid期刊信息，这个脚本可以吗？](http://lib.cqvip.com/Qikan/Journal/JournalGuid%E6%9C%9F%E5%88%8A%E4%BF%A1%E6%81%AF%EF%BC%8C%E8%BF%99%E4%B8%AA%E8%84%9A%E6%9C%AC%E5%8F%AF%E4%BB%A5%E5%90%97%EF%BC%9F)

可以，
执行
python main.py -m 2 -r 1 -t  【你要爬取的关键词】
